/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/istp.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending1.geometry}
        material={nodes.ascending1.material}
        position={[-0.009, 2.26, -0.872]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending2.geometry}
        material={nodes.ascending2.material}
        position={[0.716, 2.26, -0.872]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending3.geometry}
        material={nodes.ascending3.material}
        position={[1.404, 2.26, -0.872]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending4.geometry}
        material={nodes.ascending4.material}
        position={[2.125, 2.26, -0.872]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending5.geometry}
        material={nodes.ascending5.material}
        position={[2.862, 2.26, -0.181]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending6.geometry}
        material={nodes.ascending6.material}
        position={[2.854, 2.26, -0.872]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.descending1.geometry}
        material={nodes.descending1.material}
        position={[1.461, 2.263, -4.46]}
        scale={[0.522, 0.359, 0.359]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.descending2.geometry}
        material={nodes.descending2.material}
        position={[0.577, 2.26, -3.008]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.descending3.geometry}
        material={nodes.descending3.material}
        position={[1.258, 2.26, -3.008]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.descending4.geometry}
        material={nodes.descending4.material}
        position={[1.988, 2.26, -3.008]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['left-column'].geometry}
        material={nodes['left-column'].material}
        position={[-0.008, 2.219, -1.755]}
        scale={[0.359, 0.359, 0.507]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['right-column'].geometry}
        material={nodes['right-column'].material}
        position={[-0.113, 2.26, -3.026]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.thumb_right.geometry}
        material={nodes.thumb_right.material}
        position={[4.75, 2.25, -5.309]}
        rotation={[0, -0.358, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['thumb-big'].geometry}
        material={nodes['thumb-big'].material}
        position={[5.955, 2.253, -3.417]}
        rotation={[0, -0.351, 0]}
        scale={[0.75, 0.357, 0.366]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['thumb-top'].geometry}
        material={nodes['thumb-top'].material}
        position={[3.841, 2.25, -4.874]}
        rotation={[0, -0.355, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-0.171, 3.87, 1.167]}
        scale={3.844}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending1001.geometry}
        material={nodes.ascending1001.material}
        position={[-0.009, 2.26, -5.663]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending2001.geometry}
        material={nodes.ascending2001.material}
        position={[0.716, 2.26, -5.663]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending3001.geometry}
        material={nodes.ascending3001.material}
        position={[1.404, 2.26, -5.663]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending4001.geometry}
        material={nodes.ascending4001.material}
        position={[2.125, 2.26, -5.663]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending5001.geometry}
        material={nodes.ascending5001.material}
        position={[2.862, 2.26, -6.354]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ascending6001.geometry}
        material={nodes.ascending6001.material}
        position={[2.854, 2.26, -5.663]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.descending1001.geometry}
        material={nodes.descending1001.material}
        position={[1.461, 2.263, -2.075]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.522, -0.359, -0.359]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.descending2001.geometry}
        material={nodes.descending2001.material}
        position={[0.577, 2.26, -3.527]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.descending3001.geometry}
        material={nodes.descending3001.material}
        position={[1.258, 2.26, -3.527]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.descending4001.geometry}
        material={nodes.descending4001.material}
        position={[1.988, 2.26, -3.527]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['left-column001'].geometry}
        material={nodes['left-column001'].material}
        position={[-0.008, 2.219, -4.78]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.359, -0.359, -0.507]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['right-column001'].geometry}
        material={nodes['right-column001'].material}
        position={[-0.113, 2.26, -3.509]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.thumb_right001.geometry}
        material={nodes.thumb_right001.material}
        position={[4.75, 2.25, -1.226]}
        rotation={[0, 0.358, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['thumb-big001'].geometry}
        material={nodes['thumb-big001'].material}
        position={[5.955, 2.253, -3.118]}
        rotation={[0, 0.351, -Math.PI]}
        scale={[-0.75, -0.357, -0.366]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['thumb-top001'].geometry}
        material={nodes['thumb-top001'].material}
        position={[3.841, 2.25, -1.661]}
        rotation={[0, 0.355, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[-0.171, 3.87, -7.702]}
        rotation={[0, 0, -Math.PI]}
        scale={-3.844}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Esc.geometry}
        material={materials['Material.001']}
        position={[-1.287, 0.931, 4.248]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.one.geometry}
        material={materials['Material.003']}
        position={[-1.432, 0.976, 2.574]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tilde.geometry}
        material={materials['Material.001']}
        position={[-1.344, 1.006, 3.328]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.three.geometry}
        material={materials['Material.004']}
        position={[-1.492, 0.99, 1.126]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.two.geometry}
        material={materials['Material.005']}
        position={[-1.488, 0.987, 1.837]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.four.geometry}
        material={materials['Material.006']}
        position={[-1.44, 0.993, 0.416]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['5'].geometry}
        material={materials['Material.007']}
        position={[-1.406, 0.98, -0.307]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tab.geometry}
        material={materials['Material.008']}
        position={[-0.58, 0.931, 4.274]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.caps.geometry}
        material={materials['Material.009']}
        position={[0.037, 0.946, 4.105]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shift.geometry}
        material={materials['Material.010']}
        position={[0.841, 0.941, 4.307]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.q.geometry}
        material={materials['Material.008']}
        position={[-0.57, 0.984, 3.372]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.w.geometry}
        material={materials['Material.012']}
        position={[-0.599, 0.984, 2.642]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.e.geometry}
        material={materials['Material.013']}
        position={[-0.655, 0.984, 1.914]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.r.geometry}
        material={materials['Material.014']}
        position={[-0.686, 0.984, 1.215]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.t.geometry}
        material={materials['Material.015']}
        position={[-0.653, 0.984, 0.506]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['{'].geometry}
        material={materials['Material.016']}
        position={[-0.57, 0.984, -0.272]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.a.geometry}
        material={materials['Material.017']}
        position={[0.119, 0.984, 3.357]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s.geometry}
        material={materials['Material.018']}
        position={[0.08, 0.984, 2.624]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.d.geometry}
        material={materials['Material.019']}
        position={[0.044, 0.984, 1.939]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.f.geometry}
        material={materials['Material.001']}
        position={[-0.023, 0.984, 1.211]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.g.geometry}
        material={materials['Material.021']}
        position={[0.019, 0.984, 0.522]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fn.geometry}
        material={materials['Material.022']}
        position={[0.566, 0.984, -0.192]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.z.geometry}
        material={materials['Material.023']}
        position={[0.841, 0.984, 3.344]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.x.geometry}
        material={materials['Material.024']}
        position={[0.787, 0.984, 2.618]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.c.geometry}
        material={materials['Material.025']}
        position={[0.733, 0.984, 1.923]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.V.geometry}
        material={materials['Material.026']}
        position={[0.698, 0.984, 1.223]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.B.geometry}
        material={materials['Material.027']}
        position={[0.731, 0.984, 0.506]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ctrl.geometry}
        material={materials['Material.028']}
        position={[1.568, 0.984, 4.132]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.alt.geometry}
        material={materials['Material.029']}
        position={[1.499, 0.984, 2.699]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fn2001.geometry}
        material={materials['Material.030']}
        position={[1.55, 0.984, 3.393]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.menu.geometry}
        material={materials['Material.031']}
        position={[1.439, 0.984, 2.048]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['^'].geometry}
        material={materials['Material.032']}
        position={[1.441, 0.984, 1.197]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shift2.geometry}
        material={materials['Material.033']}
        position={[1.861, 0.984, -0.22]}
        rotation={[0, 1.225, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.home.geometry}
        material={materials['Material.034']}
        position={[1.985, 0.984, -1.682]}
        rotation={[0, 1.225, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.print.geometry}
        material={materials['Material.035']}
        position={[2.671, 0.984, -1.468]}
        rotation={[0, 1.225, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ins.geometry}
        material={materials['Material.036']}
        position={[1.142, 0.984, -1.335]}
        rotation={[0, 1.225, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pageup.geometry}
        material={materials['Material.037']}
        position={[1.336, 0.984, -2.129]}
        rotation={[0, 1.225, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['6'].geometry}
        material={materials['Material.002']}
        position={[-1.406, 0.98, -6.227]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['7'].geometry}
        material={materials['Material.011']}
        position={[-1.456, 0.98, -6.945]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['8'].geometry}
        material={materials['Material.020']}
        position={[-1.508, 0.98, -7.666]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['?'].geometry}
        material={materials['Material.038']}
        position={[0.717, 0.98, -9.801]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0'].geometry}
        material={materials['Material.039']}
        position={[-1.461, 0.981, -9.087]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._.geometry}
        material={materials['Material.040']}
        position={[-1.435, 1.002, -9.802]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backspace.geometry}
        material={materials['Material.041']}
        position={[-1.307, 0.965, -10.619]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['}'].geometry}
        material={materials['Material.042']}
        position={[-0.565, 0.98, -6.228]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.y.geometry}
        material={materials['Material.043']}
        position={[-0.666, 0.98, -6.961]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.U.geometry}
        material={materials['Material.044']}
        position={[-0.709, 0.98, -7.672]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.i.geometry}
        material={materials['Material.045']}
        position={[-0.676, 0.98, -8.369]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.O.geometry}
        material={materials['Material.046']}
        position={[-0.626, 0.98, -9.074]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.P.geometry}
        material={materials['Material.047']}
        position={[-0.574, 0.98, -9.79]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['|'].geometry}
        material={materials['Material.048']}
        position={[-0.864, 0.98, -10.609]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.h.geometry}
        material={materials['Material.049']}
        position={[0.016, 0.98, -6.965]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.J.geometry}
        material={materials['Material.050']}
        position={[-0.043, 0.98, -7.673]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.K.geometry}
        material={materials['Material.051']}
        position={[0.012, 0.98, -8.369]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.L.geometry}
        material={materials['Material.052']}
        position={[0.064, 0.98, -9.093]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes[';'].geometry}
        material={materials['Material.053']}
        position={[-0.025, 0.98, -9.806]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.enter.geometry}
        material={materials['Material.054']}
        position={[0.135, 0.98, -10.608]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+='].geometry}
        material={materials['Material.055']}
        position={[0.471, 0.98, -6.214]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.N.geometry}
        material={materials['Material.056']}
        position={[0.753, 0.98, -6.966]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.M.geometry}
        material={materials['Material.057']}
        position={[0.697, 0.98, -7.671]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['<,'].geometry}
        material={materials['Material.058']}
        position={[0.633, 0.98, -8.356]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['9'].geometry}
        material={materials['Material.059']}
        position={[-1.496, 0.98, -8.369]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['>'].geometry}
        material={materials['Material.060']}
        position={[0.688, 0.98, -9.088]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shift2001.geometry}
        material={materials['Material.061']}
        position={[0.847, 0.98, -10.601]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['9001'].geometry}
        material={materials['Material.063']}
        position={[-1.496, 0.98, -8.369]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pagedown.geometry}
        material={materials['Material.064']}
        position={[1.342, 0.984, -4.403]}
        rotation={[-Math.PI, 1.196, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.del.geometry}
        material={materials['Material.066']}
        position={[1.172, 0.984, -5.089]}
        rotation={[-Math.PI, 1.217, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.end.geometry}
        material={materials['Material.067']}
        position={[2.079, 0.984, -4.662]}
        rotation={[-Math.PI, 1.23, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fn2.geometry}
        material={materials['Material.068']}
        position={[2.723, 0.984, -4.898]}
        rotation={[-Math.PI, 1.249, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.del2.geometry}
        material={materials['Material.069']}
        position={[1.908, 0.984, -6.134]}
        rotation={[-Math.PI, 1.25, -Math.PI]}
      />
    </group>
  )
}

useGLTF.preload('/istp.glb')
