/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

import AlphakeyMat from './alphakey-mat';
import BoardMat from './board-mat';

export default function Model(props) {
  const { nodes } = useGLTF('/istp.glb')
  const group= useRef();

  return (
    <group ref= {group} {...props} dispose={null}>
      
      <directionalLight
          color={"#fffff"}
          name="DirectionalLight"
          intensity={3}
          decay={0.5}
          position={[-0.15, 7.956, -3.906]}
      />

      <directionalLight
             color={"#fffff"}
             name="DirectionalLight"
             intensity={3}
             decay={0.5}
             position={[-0.15, 7.956, -3.906]}
      />


      <mesh
        name="ascending1"
        geometry={nodes.ascending1.geometry}
        material={nodes.ascending1.material}
        position={[-0.009, 2.26, -0.872]}
        scale={0.359}
        >
      <AlphakeyMat/>
      </mesh>

 
      <mesh
        name="ascending2"
        geometry={nodes.ascending2.geometry}
        material={nodes.ascending2.material}
        position={[0.716, 2.26, -0.872]}
        scale={0.359}
      >
        <AlphakeyMat/>
        </mesh>

      <mesh
        name="ascending3"
        geometry={nodes.ascending3.geometry}
        material={nodes.ascending3.material}
        position={[1.404, 2.26, -0.872]}
        scale={0.359}
        >
        <AlphakeyMat/>
        </mesh>
      <mesh
        name="ascending4"
        geometry={nodes.ascending4.geometry}
        material={nodes.ascending4.material}
        position={[2.125, 2.26, -0.872]}
        scale={0.359}
        >
        <AlphakeyMat/>
        </mesh>
      <mesh
        name="ascending5"
        geometry={nodes.ascending5.geometry}
        material={nodes.ascending5.material}
        position={[2.862, 2.26, -0.181]}
        scale={0.359}
        >
        <AlphakeyMat/>
        </mesh>
      <mesh
        name="ascending6"
        geometry={nodes.ascending6.geometry}
        material={nodes.ascending6.material}
        position={[2.854, 2.26, -0.872]}
        scale={0.359}
        >
        <AlphakeyMat/>
        </mesh>

      <mesh
        name="descending1"
        geometry={nodes.descending1.geometry}
        material={nodes.descending1.material}
        position={[1.461, 2.263, -4.46]}
        scale={[0.522, 0.359, 0.359]}
        >
        <AlphakeyMat/>
        </mesh>
      <mesh
        name="descending2"
        geometry={nodes.descending2.geometry}
        material={nodes.descending2.material}
        position={[0.577, 2.26, -3.008]}
        scale={0.359}
        >
        <AlphakeyMat/>
        </mesh>
      <mesh
        name="descending3"
        geometry={nodes.descending3.geometry}
        material={nodes.descending3.material}
        position={[1.258, 2.26, -3.008]}
        scale={0.359}
        >
        <AlphakeyMat/>
        </mesh>
      <mesh
        name="descending4"
        geometry={nodes.descending4.geometry}
        material={nodes.descending4.material}
        position={[1.988, 2.26, -3.008]}
        scale={0.359}
        >
        <AlphakeyMat/>
        </mesh>
      <mesh
        name="left-column"
        geometry={nodes['left-column'].geometry}
        material={nodes['left-column'].material}
        position={[-0.008, 2.219, -1.755]}
        scale={[0.359, 0.359, 0.507]}
      />
      <mesh
        name="right-column"
        geometry={nodes['right-column'].geometry}
        material={nodes['right-column'].material}
        position={[-0.113, 2.26, -3.026]}
        scale={0.359}
      />
      <mesh
        name="thumb_right"
        geometry={nodes.thumb_right.geometry}
        material={nodes.thumb_right.material}
        position={[4.75, 2.25, -5.309]}
        rotation={[0, -0.358, 0]}
        scale={0.359}
      />
      <mesh
        name="thumb-big"
        geometry={nodes['thumb-big'].geometry}
        material={nodes['thumb-big'].material}
        position={[5.955, 2.253, -3.417]}
        rotation={[0, -0.351, 0]}
        scale={[0.75, 0.357, 0.366]}
      />
      <mesh
        name="thumb-top"
        geometry={nodes['thumb-top'].geometry}
        material={nodes['thumb-top'].material}
        position={[3.841, 2.25, -4.874]}
        rotation={[0, -0.355, 0]}
        scale={0.359}
      />

      <mesh
        name="Plane"
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-0.171, 3.87, 1.167]}
        scale={3.844}
      >
        <BoardMat/>
        </mesh>

      <mesh
        name="ascending1001"
        geometry={nodes.ascending1001.geometry}
        material={nodes.ascending1001.material}
        position={[-0.009, 2.26, -5.663]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="ascending2001"
        geometry={nodes.ascending2001.geometry}
        material={nodes.ascending2001.material}
        position={[0.716, 2.26, -5.663]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="ascending3001"
        geometry={nodes.ascending3001.geometry}
        material={nodes.ascending3001.material}
        position={[1.404, 2.26, -5.663]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="ascending4001"
        geometry={nodes.ascending4001.geometry}
        material={nodes.ascending4001.material}
        position={[2.125, 2.26, -5.663]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="ascending5001"
        geometry={nodes.ascending5001.geometry}
        material={nodes.ascending5001.material}
        position={[2.862, 2.26, -6.354]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="ascending6001"
        geometry={nodes.ascending6001.geometry}
        material={nodes.ascending6001.material}
        position={[2.854, 2.26, -5.663]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="descending1001"
        geometry={nodes.descending1001.geometry}
        material={nodes.descending1001.material}
        position={[1.461, 2.263, -2.075]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.522, -0.359, -0.359]}
      />
      <mesh
        name="descending2001"
        geometry={nodes.descending2001.geometry}
        material={nodes.descending2001.material}
        position={[0.577, 2.26, -3.527]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="descending3001"
        geometry={nodes.descending3001.geometry}
        material={nodes.descending3001.material}
        position={[1.258, 2.26, -3.527]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="descending4001"
        geometry={nodes.descending4001.geometry}
        material={nodes.descending4001.material}
        position={[1.988, 2.26, -3.527]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="left-column001"
        geometry={nodes['left-column001'].geometry}
        material={nodes['left-column001'].material}
        position={[-0.008, 2.219, -4.78]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.359, -0.359, -0.507]}
      />
      <mesh
        name="right-column001"
        geometry={nodes['right-column001'].geometry}
        material={nodes['right-column001'].material}
        position={[-0.113, 2.26, -3.509]}
        rotation={[0, 0, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="thumb_right001"
        geometry={nodes.thumb_right001.geometry}
        material={nodes.thumb_right001.material}
        position={[4.75, 2.25, -1.226]}
        rotation={[0, 0.358, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="thumb-big001"
        geometry={nodes['thumb-big001'].geometry}
        material={nodes['thumb-big001'].material}
        position={[5.955, 2.253, -3.118]}
        rotation={[0, 0.351, -Math.PI]}
        scale={[-0.75, -0.357, -0.366]}
      />
      <mesh
        name="thumb-top001"
        geometry={nodes['thumb-top001'].geometry}
        material={nodes['thumb-top001'].material}
        position={[3.841, 2.25, -1.661]}
        rotation={[0, 0.355, -Math.PI]}
        scale={-0.359}
      />
      <mesh
        name="Plane001"
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[-0.171, 3.87, -7.702]}
        rotation={[0, 0, -Math.PI]}
        scale={-3.844}
      >
        <BoardMat/>
        </mesh>
      <mesh
        name="Esc"
        geometry={nodes.Esc.geometry}
        material={nodes.Esc.material}
        position={[-1.287, 0.931, 4.248]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="one"
        geometry={nodes.one.geometry}
        material={nodes.one.material}
        position={[-1.432, 0.976, 2.574]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="tilde"
        geometry={nodes.tilde.geometry}
        material={nodes.tilde.material}
        position={[-1.344, 1.006, 3.328]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="three"
        geometry={nodes.three.geometry}
        material={nodes.three.material}
        position={[-1.492, 0.99, 1.126]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="two"
        geometry={nodes.two.geometry}
        material={nodes.two.material}
        position={[-1.488, 0.987, 1.837]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="four"
        geometry={nodes.four.geometry}
        material={nodes.four.material}
        position={[-1.44, 0.993, 0.416]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="5"
        geometry={nodes['5'].geometry}
        material={nodes['5'].material}
        position={[-1.406, 0.98, -0.307]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="Tab"
        geometry={nodes.Tab.geometry}
        material={nodes.Tab.material}
        position={[-0.58, 0.931, 4.274]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="caps"
        geometry={nodes.caps.geometry}
        material={nodes.caps.material}
        position={[0.037, 0.946, 4.105]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="shift"
        geometry={nodes.shift.geometry}
        material={nodes.shift.material}
        position={[0.841, 0.941, 4.307]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="q"
        geometry={nodes.q.geometry}
        material={nodes.q.material}
        position={[-0.57, 0.984, 3.372]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="w"
        geometry={nodes.w.geometry}
        material={nodes.w.material}
        position={[-0.599, 0.984, 2.642]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="e"
        geometry={nodes.e.geometry}
        material={nodes.e.material}
        position={[-0.655, 0.984, 1.914]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="r"
        geometry={nodes.r.geometry}
        material={nodes.r.material}
        position={[-0.686, 0.984, 1.215]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="t"
        geometry={nodes.t.geometry}
        material={nodes.t.material}
        position={[-0.653, 0.984, 0.506]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="leftbracket"
        geometry={nodes.leftbracket.geometry}
        material={nodes.leftbracket.material}
        position={[-0.57, 0.984, -0.272]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="a"
        geometry={nodes.a.geometry}
        material={nodes.a.material}
        position={[0.119, 0.984, 3.357]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="s"
        geometry={nodes.s.geometry}
        material={nodes.s.material}
        position={[0.08, 0.984, 2.624]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="d"
        geometry={nodes.d.geometry}
        material={nodes.d.material}
        position={[0.044, 0.984, 1.939]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="f"
        geometry={nodes.f.geometry}
        material={nodes.f.material}
        position={[-0.023, 0.984, 1.211]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="g"
        geometry={nodes.g.geometry}
        material={nodes.g.material}
        position={[0.019, 0.984, 0.522]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="leftfn2"
        geometry={nodes.leftfn2.geometry}
        material={nodes.leftfn2.material}
        position={[0.566, 0.984, -0.192]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="z"
        geometry={nodes.z.geometry}
        material={nodes.z.material}
        position={[0.841, 0.984, 3.344]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="x"
        geometry={nodes.x.geometry}
        material={nodes.x.material}
        position={[0.787, 0.984, 2.618]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="c"
        geometry={nodes.c.geometry}
        material={nodes.c.material}
        position={[0.733, 0.984, 1.923]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="V"
        geometry={nodes.V.geometry}
        material={nodes.V.material}
        position={[0.698, 0.984, 1.223]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="B"
        geometry={nodes.B.geometry}
        material={nodes.B.material}
        position={[0.731, 0.984, 0.506]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="ctrl"
        geometry={nodes.ctrl.geometry}
        material={nodes.ctrl.material}
        position={[1.568, 0.984, 4.132]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="alt"
        geometry={nodes.alt.geometry}
        material={nodes.alt.material}
        position={[1.499, 0.984, 2.699]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="leftfn"
        geometry={nodes.leftfn.geometry}
        material={nodes.leftfn.material}
        position={[1.55, 0.984, 3.393]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="menu"
        geometry={nodes.menu.geometry}
        material={nodes.menu.material}
        position={[1.439, 0.984, 2.048]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="karat"
        geometry={nodes.karat.geometry}
        material={nodes.karat.material}
        position={[1.441, 0.984, 1.197]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="shift2"
        geometry={nodes.shift2.geometry}
        material={nodes.shift2.material}
        position={[1.861, 0.984, -0.22]}
        rotation={[0, 1.225, 0]}
      />
      <mesh
        name="home"
        geometry={nodes.home.geometry}
        material={nodes.home.material}
        position={[1.985, 0.984, -1.682]}
        rotation={[0, 1.225, 0]}
      />
      <mesh
        name="print"
        geometry={nodes.print.geometry}
        material={nodes.print.material}
        position={[2.671, 0.984, -1.468]}
        rotation={[0, 1.225, 0]}
      />
      <mesh
        name="ins"
        geometry={nodes.ins.geometry}
        material={nodes.ins.material}
        position={[1.142, 0.984, -1.335]}
        rotation={[0, 1.225, 0]}
      />
      <mesh
        name="pageup"
        geometry={nodes.pageup.geometry}
        material={nodes.pageup.material}
        position={[1.336, 0.984, -2.129]}
        rotation={[0, 1.225, 0]}
      />
      <mesh
        name="6"
        geometry={nodes['6'].geometry}
        material={nodes['6'].material}
        position={[-1.406, 0.98, -6.227]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="7"
        geometry={nodes['7'].geometry}
        material={nodes['7'].material}
        position={[-1.456, 0.98, -6.945]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="8"
        geometry={nodes['8'].geometry}
        material={nodes['8'].material}
        position={[-1.508, 0.98, -7.666]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="question"
        geometry={nodes.question.geometry}
        material={nodes.question.material}
        position={[0.717, 0.98, -9.801]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="0"
        geometry={nodes['0'].geometry}
        material={nodes['0'].material}
        position={[-1.461, 0.981, -9.087]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="underscore"
        geometry={nodes.underscore.geometry}
        material={nodes.underscore.material}
        position={[-1.435, 1.002, -9.802]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="backspace"
        geometry={nodes.backspace.geometry}
        material={nodes.backspace.material}
        position={[-1.307, 0.965, -10.619]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="rightbracket"
        geometry={nodes.rightbracket.geometry}
        material={nodes.rightbracket.material}
        position={[-0.565, 0.98, -6.228]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="y"
        geometry={nodes.y.geometry}
        material={nodes.y.material}
        position={[-0.666, 0.98, -6.961]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="U"
        geometry={nodes.U.geometry}
        material={nodes.U.material}
        position={[-0.709, 0.98, -7.672]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="i"
        geometry={nodes.i.geometry}
        material={nodes.i.material}
        position={[-0.676, 0.98, -8.369]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="O"
        geometry={nodes.O.geometry}
        material={nodes.O.material}
        position={[-0.626, 0.98, -9.074]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="P"
        geometry={nodes.P.geometry}
        material={nodes.P.material}
        position={[-0.574, 0.98, -9.79]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="forwardslash"
        geometry={nodes.forwardslash.geometry}
        material={nodes.forwardslash.material}
        position={[-0.864, 0.98, -10.609]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="h"
        geometry={nodes.h.geometry}
        material={nodes.h.material}
        position={[0.016, 0.98, -6.965]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="J"
        geometry={nodes.J.geometry}
        material={nodes.J.material}
        position={[-0.043, 0.98, -7.673]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="K"
        geometry={nodes.K.geometry}
        material={nodes.K.material}
        position={[0.012, 0.98, -8.369]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="L"
        geometry={nodes.L.geometry}
        material={nodes.L.material}
        position={[0.064, 0.98, -9.093]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="colon"
        geometry={nodes.colon.geometry}
        material={nodes.colon.material}
        position={[-0.025, 0.98, -9.806]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="enter"
        geometry={nodes.enter.geometry}
        material={nodes.enter.material}
        position={[0.135, 0.98, -10.608]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="plusequal"
        geometry={nodes.plusequal.geometry}
        material={nodes.plusequal.material}
        position={[0.471, 0.98, -6.214]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="N"
        geometry={nodes.N.geometry}
        material={nodes.N.material}
        position={[0.753, 0.98, -6.966]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="M"
        geometry={nodes.M.geometry}
        material={nodes.M.material}
        position={[0.697, 0.98, -7.671]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="leftpoint"
        geometry={nodes.leftpoint.geometry}
        material={nodes.leftpoint.material}
        position={[0.633, 0.98, -8.356]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="9"
        geometry={nodes['9'].geometry}
        material={nodes['9'].material}
        position={[-1.496, 0.98, -8.369]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="rightpoint"
        geometry={nodes.rightpoint.geometry}
        material={nodes.rightpoint.material}
        position={[0.688, 0.98, -9.088]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="shift2001"
        geometry={nodes.shift2001.geometry}
        material={nodes.shift2001.material}
        position={[0.847, 0.98, -10.601]}
        rotation={[0, 1.566, 0]}
      />
      <mesh
        name="pagedown"
        geometry={nodes.pagedown.geometry}
        material={nodes.pagedown.material}
        position={[1.342, 0.984, -4.403]}
        rotation={[-Math.PI, 1.196, -Math.PI]}
      />
      <mesh
        name="del"
        geometry={nodes.del.geometry}
        material={nodes.del.material}
        position={[1.172, 0.984, -5.089]}
        rotation={[-Math.PI, 1.217, -Math.PI]}
      />
      <mesh
        name="end"
        geometry={nodes.end.geometry}
        material={nodes.end.material}
        position={[2.079, 0.984, -4.662]}
        rotation={[-Math.PI, 1.23, -Math.PI]}
      />
      <mesh
        name="rightfn"
        geometry={nodes.rightfn.geometry}
        material={nodes.rightfn.material}
        position={[2.723, 0.984, -4.898]}
        rotation={[-Math.PI, 1.249, -Math.PI]}
      />
      <mesh
        name="del2"
        geometry={nodes.del2.geometry}
        material={nodes.del2.material}
        position={[1.908, 0.984, -6.134]}
        rotation={[-Math.PI, 1.25, -Math.PI]}
      />
      <PerspectiveCamera
        name="Camera"
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[16.429, 21.209, 0.216]}
        rotation={[-1.411, 0.661, 1.313]}
        scale={1.453}
      />
    </group>
  )
}

useGLTF.preload('/istp.glb')
