/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/4-button-key.glb 
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';



export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/4-button-key.glb')

  //on hover



  //on click
  const handleClick = (event) => {
    const meshName= event.object.name;
    switch(meshName) {
      case 'Key1':
        window.location.href= '/';
        break;
      
      case 'Key2':
        window.location.href= '/Quiz';
        break; 
      
      case 'Key3':
        window.location.href= '/About';
        break;
        
      default:
        break;
    }
  };

  useEffect(() => {
    const currentGroup = group.current;

    currentGroup.children.forEach((child) => {
      child.addEventListener('click', handleClick);
      child.addEventListener('hover', handleHover);

    });

    return () => {
      currentGroup.children.forEach((child) => {
        child.removeEventListener('click', handleClick);
        child.removeEventListener('hover', handleHover);

      });
    };
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="BezierCurve"
          position={[-5.778, 0.405, -2.069]}
          rotation={[0, 0.178, -Math.PI]}
          scale={[-1.038, -1, -0.516]}
        />
        <mesh
          name="Connection"
          geometry={nodes.Connection.geometry}
          material={materials["Material.007"]}
          position={[-2.447, 0.571, 0.012]}
          rotation={[-0.834, 0.062, 1.582]}
          scale={[1.178, 1.001, 1.166]}
        />
        <mesh
          name="Cable"
          geometry={nodes.Cable.geometry}
          material={materials["Material.006"]}
          position={[-7.266, 2.444, -0.324]}
          rotation={[0, 0.009, 0]}
          scale={[1.39, 1, 1]}
        />

        <mesh
          name="Key1"
          onClick={handleClick}
          geometry={nodes.Key1.geometry}
          material={materials["Material.002"]}
          position={[-1, 0.998, 0.993]}
        />
        <mesh
          name="Key2"
          onClick={handleClick}
          geometry={nodes.Key2.geometry}
          material={materials["Material.003"]}
          position={[-1, 0.998, -0.973]}
        />
        <mesh
          name="Key3"
          onClick={handleClick}
          geometry={nodes.Key3.geometry}
          material={materials["Material.004"]}
          position={[0.984, 0.998, 0.993]}
        />
        <mesh
          name="Key4"
          geometry={nodes.Key4.geometry}
          material={materials["Material.005"]}
          position={[0.984, 0.998, -0.973]}
          scale={1.034}
        />
        <mesh
          name="Base"
          geometry={nodes.Base.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/4-button-key.glb')
