/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/4-button-key.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/4-button-key.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Connection.geometry} material={materials['Material.007']} position={[-2.447, 0.571, 0.012]} rotation={[-0.834, 0.062, 1.582]} scale={[1.178, 1.001, 1.166]} />
      <mesh geometry={nodes.Cable.geometry} material={materials['Material.006']} position={[-6.599, 2.444, -0.324]} rotation={[0, 0.009, 0]} scale={[1.27, 1, 1]} />
      <mesh geometry={nodes.Key1.geometry} material={materials['Material.002']} position={[-1, 0.825, 0.993]} />
      <mesh geometry={nodes.Key2.geometry} material={materials['Material.003']} position={[-1, 0.825, -0.973]} />
      <mesh geometry={nodes.Key3.geometry} material={materials['Material.004']} position={[0.984, 0.825, 0.993]} />
      <mesh geometry={nodes.Key4.geometry} material={materials['Material.005']} position={[0.984, 0.825, -0.973]} scale={1.034} />
      <mesh geometry={nodes.Base.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/4-button-key.glb')
