/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/startswitch.glb 
*/

import React, { useRef, useLayoutEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
//import { useNavigate } from 'react-router-dom';


export default function Model(props) {
  const group = useRef()
  const { nodes, animations } = useGLTF('/startswitch.glb')
  const { actions, names } = useAnimations(animations, group);
  //const navigate= useNavigate();

useLayoutEffect(() => {
  const animationName= "Plane.001Action";

  if(actions[animationName]){
    actions[animationName].play();
  }
}, [actions, names]);



  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" position= {[-20, 0, -20]} scale={7}>
        <mesh 
          name="Plane" 
          geometry={nodes.Plane.geometry} 
          material={nodes.Plane.material}
        />

        <mesh 
          name="Cube" 
          geometry={nodes.Cube.geometry} 
          material={nodes.Cube.material} 
          position={[0, 0.159, 0]} 
          scale={0.5} 
        /> 
        
        <mesh 
          name="Plane001" 
          geometry={nodes.Plane001.geometry} 
          material={nodes.Plane001.material} 
          position={[0, 0.764, 0]}
        />

      </group> 
    </group>
  )
}

useGLTF.preload('/startswitch.glb')
